#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Copyright 2025 SSH Tunnel Manager Contributors
#
# Tier-2 live SSH fixture: an unprivileged sshd on localhost.
#
#   scripts/ssh-fixture.sh up      start it and write .local/testing/ssh-target.env
#   scripts/ssh-fixture.sh down    stop it and delete everything it generated
#   scripts/ssh-fixture.sh status  report whether it is running
#
# No root, no container, no secrets, nothing to install: OpenSSH's sshd runs
# perfectly well as a normal user on a high port with its own config and host
# key. Every credential is generated per run and thrown away on `down`.
#
# What this covers -- the six live tests that need only a host key and public
# key authentication:
#
#   first_connection_prompts_for_host_key_and_remembers_it
#   a_changed_host_key_is_refused
#   key_authentication_connects_and_forwards_traffic
#   an_encrypted_key_prompts_for_its_passphrase
#   stopping_a_connected_tunnel_returns_promptly
#   stopping_during_authentication_returns_promptly
#
# What it cannot cover: password and 2FA authentication. Both go through PAM,
# which needs to read the shadow database, which needs privilege. Those four
# tests skip here and run in tier 4 against a provisioned host -- see
# scripts/provision-test-target.sh.
#
# Run the tier with SSH_TUNNEL_TEST_STRICT=1 so a missing fixture fails loudly
# instead of skipping every test and reporting "ok".

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TESTING_DIR="$REPO_ROOT/.local/testing"
FIXTURE_DIR="$TESTING_DIR/fixture"
ENV_FILE="$TESTING_DIR/ssh-target.env"
PID_FILE="$FIXTURE_DIR/sshd.pid"

say() { printf '\033[0;34m==>\033[0m %s\n' "$1"; }
ok()  { printf '\033[0;32m  ok\033[0m %s\n' "$1"; }
die() { printf '\033[0;31merror:\033[0m %s\n' "$1" >&2; exit 1; }

find_sshd() {
    for c in /usr/sbin/sshd /usr/bin/sshd "$(command -v sshd 2>/dev/null || true)"; do
        [ -n "$c" ] && [ -x "$c" ] && { echo "$c"; return; }
    done
    die "sshd not found. Install openssh-server (Debian/Ubuntu) or openssh-server (Fedora)."
}

free_port() {
    python3 -c 'import socket;s=socket.socket();s.bind(("127.0.0.1",0));print(s.getsockname()[1]);s.close()'
}

cmd_down() {
    if [ -f "$PID_FILE" ]; then
        local pid; pid="$(cat "$PID_FILE")"
        if kill -0 "$pid" 2>/dev/null; then
            kill "$pid" 2>/dev/null || true
            ok "stopped sshd (pid $pid)"
        fi
    fi
    rm -rf "$FIXTURE_DIR"
    # Only remove the env file if it is this fixture's, never a real target's.
    if [ -f "$ENV_FILE" ] && grep -q '^# GENERATED by scripts/ssh-fixture.sh' "$ENV_FILE"; then
        rm -f "$ENV_FILE"
        ok "removed $ENV_FILE"
    fi
    # Put back whatever `up` displaced.
    if [ -f "$ENV_FILE.real" ]; then
        mv "$ENV_FILE.real" "$ENV_FILE"
        ok "restored the previous target config to $ENV_FILE"
    fi
}

cmd_status() {
    if [ -f "$PID_FILE" ] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
        echo "running (pid $(cat "$PID_FILE"), port $(cat "$FIXTURE_DIR/port" 2>/dev/null || echo '?'))"
    else
        echo "not running"
    fi
}

cmd_up() {
    local sshd; sshd="$(find_sshd)"
    cmd_down >/dev/null 2>&1 || true

    mkdir -p "$FIXTURE_DIR"; chmod 700 "$TESTING_DIR" "$FIXTURE_DIR"
    local port; port="$(free_port)"
    echo "$port" > "$FIXTURE_DIR/port"

    say "Generating fixture keys"
    # `head -c` on the source, not the sink: piping /dev/urandom into `head`
    # gives `tr` a SIGPIPE, which `set -o pipefail` turns into a failure.
    local passphrase
    passphrase="$(head -c 512 /dev/urandom | LC_ALL=C tr -dc 'A-Za-z0-9' | cut -c1-24)"

    ssh-keygen -q -t ed25519 -f "$FIXTURE_DIR/hostkey"   -N "" -C "fixture-host"
    ssh-keygen -q -t ed25519 -f "$FIXTURE_DIR/id_key"    -N "" -C "fixture-key"
    ssh-keygen -q -t ed25519 -f "$FIXTURE_DIR/id_enc"    -N "$passphrase" -C "fixture-encrypted"
    cat "$FIXTURE_DIR/id_key.pub" "$FIXTURE_DIR/id_enc.pub" > "$FIXTURE_DIR/authorized_keys"
    chmod 600 "$FIXTURE_DIR"/*
    ok "keys generated"

    say "Writing sshd config"
    # StrictModes no: the fixture lives under the repo, whose ownership and mode
    # sshd would otherwise refuse. UsePAM no: an unprivileged sshd cannot read
    # the shadow database anyway, and leaving PAM on only adds failure modes.
    cat > "$FIXTURE_DIR/sshd_config" <<CFG
Port $port
ListenAddress 127.0.0.1
HostKey $FIXTURE_DIR/hostkey
PidFile $PID_FILE
AuthorizedKeysFile $FIXTURE_DIR/authorized_keys
PubkeyAuthentication yes
PasswordAuthentication no
KbdInteractiveAuthentication no
UsePAM no
StrictModes no
AllowTcpForwarding yes
PermitTTY yes
LogLevel VERBOSE
Subsystem sftp internal-sftp
CFG
    ok "config written"

    say "Starting sshd on 127.0.0.1:$port"
    "$sshd" -f "$FIXTURE_DIR/sshd_config" -E "$FIXTURE_DIR/sshd.log"

    # Wait for the listener rather than sleeping a guessed interval.
    local waited=0
    until python3 -c "
import socket,sys
s=socket.socket(); s.settimeout(0.3)
sys.exit(0 if s.connect_ex(('127.0.0.1',$port))==0 else 1)" 2>/dev/null; do
        waited=$((waited + 1))
        [ "$waited" -gt 50 ] && { cat "$FIXTURE_DIR/sshd.log" >&2; die "sshd did not start"; }
        sleep 0.1
    done
    ok "listening (pid $(cat "$PID_FILE"))"

    # Never clobber a real target's configuration. The provisioned-host tiers use the same
    # path, and that file holds credentials generated once during provisioning -- overwriting
    # it silently loses them, and the only symptom is `make test-live` skipping every test
    # while still reporting "ok".
    if [ -f "$ENV_FILE" ] && ! grep -q '^# GENERATED by scripts/ssh-fixture.sh' "$ENV_FILE"; then
        mv "$ENV_FILE" "$ENV_FILE.real"
        ok "preserved existing target config as $ENV_FILE.real (restored by \`down\`)"
    fi

    say "Writing $ENV_FILE"
    # The forward target is the fixture's own sshd: the test reads the
    # "SSH-2.0-..." banner back through the tunnel, so nothing else is needed.
    #
    # Password and 2FA accounts are deliberately absent -- see the header. Those
    # tests skip unless SSH_TUNNEL_TEST_STRICT=all.
    cat > "$ENV_FILE" <<ENV
# GENERATED by scripts/ssh-fixture.sh - do not commit, do not edit.
# Unprivileged localhost sshd. Key-based tests only; see the script header.

SSH_TUNNEL_TEST_HOST=127.0.0.1
SSH_TUNNEL_TEST_PORT=$port

SSH_TUNNEL_TEST_FORWARD_HOST=127.0.0.1
SSH_TUNNEL_TEST_FORWARD_PORT=$port

SSH_TUNNEL_TEST_USER_KEY=$(id -un)
SSH_TUNNEL_TEST_KEY_PATH=$FIXTURE_DIR/id_key

SSH_TUNNEL_TEST_ENCRYPTED_KEY_PATH=$FIXTURE_DIR/id_enc
SSH_TUNNEL_TEST_KEY_PASSPHRASE=$passphrase
ENV
    chmod 600 "$ENV_FILE"
    ok "$ENV_FILE written (0600)"

    echo
    say "Fixture up. Run the key-based live tests with:"
    echo "    SSH_TUNNEL_TEST_STRICT=1 cargo test -p ssh-tunnel-daemon --test live_ssh -- --ignored"
    say "Stop it with: scripts/ssh-fixture.sh down"
}

case "${1:-}" in
    up)     cmd_up ;;
    down)   cmd_down ;;
    status) cmd_status ;;
    *) sed -n '4,12p' "$0"; exit 1 ;;
esac
